version: '2'
services:
  cr.aktivco.ru-dotnet:
    container_name: cr.aktivco.ru-dotnet
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    restart: always
    volumes:
      - /docker_sys/cr.aktivco.ru/var/app:/app
      - /docker_sys/cr.aktivco.ru/var/migrator:/migrator
    links:
      - cr.aktivco.ru-psql:cr.aktivco.ru-psql
    ports:
      - 88:80
    tty: true
  cr.aktivco.ru-psql:
    container_name: cr.aktivco.ru-psql
    image: postgres
    environment:
      POSTGRES_PASSWORD: Eklmn15
      POSTGRES_USER: user
      POSTGRES_DB: db
    restart: always
    volumes:
      - /docker_sys/cr.aktivco.ru/var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 54328:5432
